apiVersion: apps/v1
kind: Deployment

metadata:
  name: controller-deploy
  labels:
    app: controller
spec:
  replicas: 2
  selector:
    matchLabels:
      app: controller
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
      - name: controller
        image: controller
        ports:
        - containerPort: 5000
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /status
            port: 5000
          initialDelaySeconds: 300
          periodSeconds: 5