apiVersion: apps/v1
kind: Deployment

metadata:
  name: dog-deploy
  labels:
    app: dog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dog
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: dog
    spec:
      containers:
      - name: dog
        image: dog
        ports:
        - containerPort: 5000
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /status
            port: 5000
          initialDelaySeconds: 300
          periodSeconds: 5