apiVersion: apps/v1
kind: Deployment

metadata:
  name: cat-deploy
  labels:
    app: cat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cat
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: cat
    spec:
      containers:
      - name: cat
        image: cat
        ports:
        - containerPort: 5000
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /status
            port: 5000
          initialDelaySeconds: 300
          periodSeconds: 5